---

- name: Get Mailman user group ID
  getent:
    database: passwd
    key: "{{ __mailman3_user_name }}"

- name: Get Mailman user group name
  getent:
    database: group
    key: "{{ getent_passwd[__mailman3_user_name][2] }}"

- name: Set Mailman user group fact
  set_fact:
    __mailman3_group_name: "{{ getent_group | first }}"
